<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
/**
* Response message helper function used in app
* Contains response messages with their corresponding message code
* version: 2.0 (24-08-2018)
*/

/**
 * Get message from codes
 * Modified in ver 2.0
 */



function get_response_message($msg_code){
    $CI =& get_instance();
    $message_arr = array(
        
        100 => "Invalid API key",
        101 => "Invalid token",
        // 102 => "Invalid Email or Password",
        102 => $CI->lang->line('response_invalid_login'),
        103 => "User authentication successfully done",
        104 => $CI->lang->line('response_user_not_found'),
        105 => $CI->lang->line('response_account_create'),
        106 => "No record found",
        107 => $CI->lang->line('response_something_went_wrong'),  //something went wrong
        108 => "You are currently not authorised to login",
        109 => $CI->lang->line('response_invalid_req'),
        110 => "Header field is missing.",
        111 => "Header value is not valid",
        112 => $CI->lang->line('response_invalid_token'),
        113 => "Your account is associated with social account",
        114 => $CI->lang->line('response_social_id_required'),
        115 => $CI->lang->line('response_social_type_required'),
        116 => $CI->lang->line('response_device_id'),

        117 => $CI->lang->line('response_step'),
        118 => $CI->lang->line('response_skip'),
        119 => "status is required.",



        120 => $CI->lang->line('response_send_pass_email'),
        121 => $CI->lang->line('response_login'),
        122 => $CI->lang->line('response_added'),
        123 => $CI->lang->line('response_update'),
        124 => $CI->lang->line('response_delete'),
        125 => $CI->lang->line('response_logout'),
        126 => "You are not authorised for this action",
        127 => $CI->lang->line('response_add_car'),
        128 => $CI->lang->line('response_pass_req'),
        129 => $CI->lang->line('response_old_pass'),
        130 => $CI->lang->line('response_cnfm_pass_req'),
        131 => $CI->lang->line('response_invalid_method'),
        132 => $CI->lang->line('response_feedback'),
        133 => $CI->lang->line('response_first_name_req'),
        134 => $CI->lang->line('response_last_name_req'),
        135 => $CI->lang->line('response_dob_req'),
        136 => $CI->lang->line('response_account_num_req'),
        137 => $CI->lang->line('response_routing_num_req'),
        138 => $CI->lang->line('response_id_not_exits'),
        139 => $CI->lang->line('response_id_exits'),
        140 => $CI->lang->line('response_type'),
        141 => $CI->lang->line('response_swap'),
        142 => $CI->lang->line('response_swap_id'),
        143 => $CI->lang->line('response_card_not_found'),
        144 => $CI->lang->line('response_ retrieved successfully'),
        145 => $CI->lang->line('response_language_req'),




        200 => 'OK',
        201 => $CI->lang->line('response_create'),
        202 => 'Accepted',
        203 => 'Non-Authoritative Information',
        204 => 'No Content',
        205 => 'Reset Content',
        206 => 'Partial Content',

        300 => 'Multiple Choices',
        301 => 'Moved Permanently',
        302 =>  $CI->lang->line('response_found'),
        303 => 'See Other',
        304 => 'Not Modified',
        305 => 'Use Proxy',
        306 => '(Unused)',
        307 => 'Temporary Redirect',
        308 =>  $CI->lang->line('response_invalid_request'),
        309 => 'sucessfully redirect',
        310 => $CI->lang->line('response_social_id_exits'),
        311 => $CI->lang->line('response_successfully_add'),
        312 =>  $CI->lang->line('response_card_successfully_add'),
        313 => $CI->lang->line('response_lat_req'),
        314 => $CI->lang->line('response_long_req'),
        315 => $CI->lang->line('response_select_swap'),
        316 => $CI->lang->line('response_select_connection'),
        317 => $CI->lang->line('response_swap_id'),
        318 => $CI->lang->line('response_gratuity_amount'),
        319 => $CI->lang->line('response_card_id'),
        320 => $CI->lang->line('response_updated_successfully'),
        321 => $CI->lang->line('response_alert_id'),

        400 => 'Bad Request',
        401 => 'Unauthorized',
        402 => 'Payment Required',
        403 => 'Forbidden',
        404 =>  $CI->lang->line('response_not_found'),
        405 => 'Method Not Allowed',
        406 => 'Not Acceptable',
        407 => 'Proxy Authentication Required',
        408 => 'Request Timeout',
        409 => 'Conflict',
        410 => 'Gone',
        411 => 'Length Required',
        412 => 'Precondition Failed',
        413 => 'Request Entity Too Large',
        414 => 'Request-URI Too Long',
        415 => 'Unsupported Media Type',
        416 => 'Requested Range Not Satisfiable',
        417 => 'Expectation Failed',

        500 => 'Internal Server Error',
        501 => 'Not Implemented',
        502 => 'Bad Gateway',
        503 => 'Service Unavailable',
        504 => 'Gateway Timeout',
        505 => 'HTTP Version Not Supported',
        506 =>  $CI->lang->line('response_email_required'),
        507 =>  $CI->lang->line('response_match_pass'),
        508 =>  $CI->lang->line('response_email_exist'),
        509 => 'Phone number already exist',
        510 => 'Verfication code sent successfully',
        511 =>  $CI->lang->line('response_token_exp'),
        512 =>  $CI->lang->line('response_user_inactive'),
        513 =>  $CI->lang->line('response_device_id'),
        514 =>  $CI->lang->line('response_device_type'),
        515 =>  $CI->lang->line('response_device_type_should'),
        516 => 'Timezone is required',
        517 => 'Verification code does not exist',
        518 => 'Verification code verified successfully',
        519 => 'Eithier email or phone number is required',
        520 => 'Phoner number does not exist',
        521 =>  $CI->lang->line('response_email_does_not_exist'),
        522 =>  $CI->lang->line('response_password_sent'),
        523 =>  $CI->lang->line('response_password'),
        524 => 'Your phone number is wrong',
        525 =>  $CI->lang->line('response_wrong_email'),
        526 =>  $CI->lang->line('response_invalid_login'),
        527 => 'Invalid Phone number/Password',
        527 =>  $CI->lang->line('response_invalid_type'),
        528 =>  $CI->lang->line('response_new_cnfmpass_req'),
        529 =>  $CI->lang->line('response_update_pass'),
        530 =>  $CI->lang->line('response_invalid_email'),
        531 => 'Invalid phone number',
        532 =>  $CI->lang->line('response_update_email'),
        533 => 'Phone number updated successfully',
        534 => 'Title should not be empty',
        535 => 'Address should not be empty',
        536 =>  $CI->lang->line('response_invalid_lat'),
        537 =>  $CI->lang->line('response_invalid_log'),
        538 => 'Invalid push alert status',
        539 => 'Invalid email alert status',
        540 => 'Invalid location',
        541 => 'Alert location addedd successfully',
        542 => 'Alert location updated successfully',
        543 => 'Invalid push setting id',
        544 => 'Invalid suspicious activity alert',
        545 => 'Invalid new message alert',
        546 => 'Invalid new follow alert',
        547 => 'Invalid alert radius',
        548 => 'Push setting updated successfully',
        549 => 'Push id does not exist',
        550 => "Param is missing",
        551 => "Please Use lower case character and number",
        552 => "Username already exist",
        553 => "Username is available",
        554 => "Username is required",
        555 => "Valid name is required",
        556 => $CI->lang->line('response_update_profile'),
        557 => "Profile picture required",
        558 => $CI->lang->line('response_image'),
        559 => "Profile picture updated successfully",
        560 => $CI->lang->line('response_invalid_lat'),
        561 => $CI->lang->line('response_invalid_log'),
        562 => $CI->lang->line('response_profile_alreay_upd'),
        563 => $CI->lang->line('response_invalid_gender'),
        564 => $CI->lang->line('response_comp_prev_step'),
        565 => $CI->lang->line('response_invalid_social_type'),
        566 => $CI->lang->line('response_old_pass_match'),

        600 => $CI->lang->line('response_make_required'),
        601 => $CI->lang->line('response_model_required'),
        602 => $CI->lang->line('response_color_required'),
        603 => $CI->lang->line('response_plate_required'),
        604 => $CI->lang->line('response_car_details'),
        605 => $CI->lang->line('response_stripe_id_exist'),
        606 => $CI->lang->line('response_stripe_card_id_exist'),
        607 => $CI->lang->line('response_default'),
        608 => $CI->lang->line('response_id_exist'),
        609 => $CI->lang->line('response_make_default'),
        610 => $CI->lang->line('response_remove_default'),
        611 => $CI->lang->line('response_success'),
        612 => $CI->lang->line('response_add_car'),
        613 => $CI->lang->line('response_add_bank'),
        614 => $CI->lang->line('response_add_card'),
        615 => $CI->lang->line('response_looking'),
        616 => $CI->lang->line('response_leaving'),
        617 => $CI->lang->line('response_account'),
        618 => $CI->lang->line('response_Card'),
        619 => $CI->lang->line('location_required'),
        620 => $CI->lang->line('invalid_stripe_id'),
        621 => $CI->lang->line('response_swap_id_req'),
        622 => $CI->lang->line('account_already_verified'),
        623 => $CI->lang->line('invalid_account_id'),
        624 => $CI->lang->line('lat_long_req'),
        625 => $CI->lang->line('response_verify_account'),
        626 => $CI->lang->line('response_not_verify_account'),
        627 => $CI->lang->line('response_stripe_connect_id_not_found'),
        628 => $CI->lang->line('error_trans_get'),
        629 => $CI->lang->line('verification_req')

    );
    
    $no_msg = '';
    if(!array_key_exists($msg_code,$message_arr)){
        return $no_msg; //code does not exist, return empty string
    }
    
    return $message_arr[$msg_code];  //return message corresponding to code
}